require("plugins.configuration.cmp")
require("plugins.configuration.telescope")
require("plugins.configuration.treesitter")
require("plugins.configuration.vimtex")
require("plugins.configuration.dap")
require("plugins.configuration.overseer")
