[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]

[font.normal]
# family = "UbuntuMono Nerd Font"
# family = "Inconsolata Nerd Font Mono"
family = "Hasklug Nerd Font Mono"

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
